# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Discriminating Between Similar Languages - Speech (DSL-S 2023)
subtitle: > # ignore newlines until "description:"
  Shared task web page.
description: > # ignore newlines until "baseurl:"
  Web page of the DSL-S shared task at Vardial 2023.
baseurl: ""
url: "https://dsl-s.github.io"
github_username: dsl-s
encoding: utf-8
future: true

# Build settings
markdown: kramdown
